const DATA_INIT_USERS = 'DATA_INIT_USERS'
const DATA_INIT_POSTS = 'DATA_INIT_POSTS'
const DATA_INIT_COMMENTS = 'DATA_INIT_COMMENTS'

const ADD_POST = 'ADD_POST'
const REMOVE_POST = 'REMOVE_POST'

const ADD_COMMENT = 'ADD_COMMENT'

export default {
  DATA_INIT_USERS,
  DATA_INIT_POSTS,
  DATA_INIT_COMMENTS,
  ADD_POST,
  REMOVE_POST,
  ADD_COMMENT
}
